version: "3.8"

services:

  postgres:
    image: postgres
    restart: always
    networks:
      - skynet_network
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=manu
      - POSTGRES_PASSWORD=Admin123
      - POSTGRES_DB=tottem
    volumes:
      - ../postgres-data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    networks:
      - skynet_network
    ports:
      - "80:80"
    depends_on:
      - postgres
    volumes:
      - ../postgres-data/