from src.DataBase import CRUD

CRUD.insertTotalServicios()
CRUD.insertZone(5)
CRUD.insertHomeType(4)
CRUD.insertClients(100)
CRUD.insertDepts()
CRUD.insertCharges()
CRUD.insertTotalEmployes()
CRUD.insertPostulants(50)
CRUD.insertPerformance(10)
CRUD.insertSalary()
CRUD.insertGrades()
CRUD.insertClientService()
CRUD.insertEmployeePerformance()
CRUD.insertClientEmployer()